export const countries = [
  {
    code: "AD",
    code3: "AND",
    flag: "/flags/ad.svg",
    name: "Andorra",
    phoneCode: "376",
    shortName: "Andorra",
  },
  {
    code: "AE",
    code3: "ARE",
    flag: "/flags/ae.svg",
    name: "United Arab Emirates",
    phoneCode: "971",
    shortName: "United Arab Emirates",
  },
  {
    code: "AF",
    code3: "AFG",
    flag: "/flags/af.svg",
    name: "Afghanistan",
    phoneCode: "93",
    shortName: "Afghanistan",
  },
  {
    code: "AG",
    code3: "ATG",
    flag: "/flags/ag.svg",
    name: "Antigua and Barbuda",
    phoneCode: "1268",
    shortName: "Antigua and Barbuda",
  },
  {
    code: "AI",
    code3: "AIA",
    flag: "/flags/ai.svg",
    name: "Anguilla",
    phoneCode: "1264",
    shortName: "Anguilla",
  },
  {
    code: "AL",
    code3: "ALB",
    flag: "/flags/al.svg",
    name: "Albania",
    phoneCode: "355",
    shortName: "Albania",
  },
  {
    code: "AM",
    code3: "ARM",
    flag: "/flags/am.svg",
    name: "Armenia",
    phoneCode: "374",
    shortName: "Armenia",
  },
  {
    code: "AO",
    code3: "AGO",
    flag: "/flags/ao.svg",
    name: "Angola",
    phoneCode: "244",
    shortName: "Angola",
  },
  {
    code: "AQ",
    code3: "ATA",
    flag: "/flags/aq.svg",
    name: "Antarctica",
    phoneCode: "672",
    shortName: "Antarctica",
  },
  {
    code: "AR",
    code3: "ARG",
    flag: "/flags/ar.svg",
    name: "Argentina",
    phoneCode: "54",
    shortName: "Argentina",
  },
  {
    code: "AS",
    code3: "ASM",
    flag: "/flags/as.svg",
    name: "American Samoa",
    phoneCode: "1684",
    shortName: "American Samoa",
  },
  {
    code: "AT",
    code3: "AUT",
    flag: "/flags/at.svg",
    name: "Austria",
    phoneCode: "43",
    shortName: "Austria",
  },
  {
    code: "AU",
    code3: "AUS",
    flag: "/flags/au.svg",
    name: "Australia",
    phoneCode: "61",
    shortName: "Australia",
  },
  {
    code: "AW",
    code3: "ABW",
    flag: "/flags/aw.svg",
    name: "Aruba",
    phoneCode: "297",
    shortName: "Aruba",
  },
  {
    code: "AX",
    code3: "ALA",
    flag: "/flags/ax.svg",
    name: "Åland Islands",
    phoneCode: "358",
    shortName: "Åland Islands",
  },
  {
    code: "AZ",
    code3: "AZE",
    flag: "/flags/az.svg",
    name: "Azerbaijan",
    phoneCode: "994",
    shortName: "Azerbaijan",
  },
  {
    code: "BA",
    code3: "BIH",
    flag: "/flags/ba.svg",
    name: "Bosnia and Herzegovina",
    phoneCode: "387",
    shortName: "Bosnia and Herzegovina",
  },
  {
    code: "BB",
    code3: "BRB",
    flag: "/flags/bb.svg",
    name: "Barbados",
    phoneCode: "1246",
    shortName: "Barbados",
  },
  {
    code: "BD",
    code3: "BGD",
    flag: "/flags/bd.svg",
    name: "Bangladesh",
    phoneCode: "880",
    shortName: "Bangladesh",
  },
  {
    code: "BE",
    code3: "BEL",
    flag: "/flags/be.svg",
    name: "Belgium",
    phoneCode: "32",
    shortName: "Belgium",
  },
  {
    code: "BF",
    code3: "BFA",
    flag: "/flags/bf.svg",
    name: "Burkina Faso",
    phoneCode: "226",
    shortName: "Burkina Faso",
  },
  {
    code: "BG",
    code3: "BGR",
    flag: "/flags/bg.svg",
    name: "Bulgaria",
    phoneCode: "359",
    shortName: "Bulgaria",
  },
  {
    code: "BH",
    code3: "BHR",
    flag: "/flags/bh.svg",
    name: "Bahrain",
    phoneCode: "973",
    shortName: "Bahrain",
  },
  {
    code: "BI",
    code3: "BDI",
    flag: "/flags/bi.svg",
    name: "Burundi",
    phoneCode: "257",
    shortName: "Burundi",
  },
  {
    code: "BJ",
    code3: "BEN",
    flag: "/flags/bj.svg",
    name: "Benin",
    phoneCode: "229",
    shortName: "Benin",
  },
  {
    code: "BL",
    code3: "BLM",
    flag: "/flags/bl.svg",
    name: "Saint Barthélemy",
    phoneCode: "590",
    shortName: "Saint Barthélemy",
  },
  {
    code: "BM",
    code3: "BMU",
    flag: "/flags/bm.svg",
    name: "Bermuda",
    phoneCode: "1441",
    shortName: "Bermuda",
  },
  {
    code: "BN",
    code3: "BRN",
    flag: "/flags/bn.svg",
    name: "Brunei Darussalam",
    phoneCode: "673",
    shortName: "Brunei",
  },
  {
    code: "BO",
    code3: "BOL",
    flag: "/flags/bo.svg",
    name: "Bolivia, Plurinational State of",
    phoneCode: "591",
    shortName: "Bolivia",
  },
  {
    code: "BQ",
    code3: "BES",
    flag: "/flags/bq.svg",
    name: "Bonaire, Sint Eustatius and Saba",
    phoneCode: "599",
    shortName: "Bonaire, Sint Eustatius and Saba",
  },
  {
    code: "BR",
    code3: "BRA",
    flag: "/flags/br.svg",
    name: "Brazil",
    phoneCode: "55",
    shortName: "Brazil",
  },
  {
    code: "BS",
    code3: "BHS",
    flag: "/flags/bs.svg",
    name: "Bahamas",
    phoneCode: "1242",
    shortName: "Bahamas",
  },
  {
    code: "BT",
    code3: "BTN",
    flag: "/flags/bt.svg",
    name: "Bhutan",
    phoneCode: "975",
    shortName: "Bhutan",
  },
  {
    code: "BV",
    code3: "BVT",
    flag: "/flags/bv.svg",
    name: "Bouvet Island",
    phoneCode: "47",
    shortName: "Bouvet Island",
  },
  {
    code: "BW",
    code3: "BWA",
    flag: "/flags/bw.svg",
    name: "Botswana",
    phoneCode: "267",
    shortName: "Botswana",
  },
  {
    code: "BY",
    code3: "BLR",
    flag: "/flags/by.svg",
    name: "Belarus",
    phoneCode: "375",
    shortName: "Belarus",
  },
  {
    code: "BZ",
    code3: "BLZ",
    flag: "/flags/bz.svg",
    name: "Belize",
    phoneCode: "501",
    shortName: "Belize",
  },
  {
    code: "CA",
    code3: "CAN",
    flag: "/flags/ca.svg",
    name: "Canada",
    phoneCode: "1",
    shortName: "Canada",
  },
  {
    code: "CC",
    code3: "CCK",
    flag: "/flags/cc.svg",
    name: "Cocos (Keeling) Islands",
    phoneCode: "61",
    shortName: "Cocos (Keeling) Islands",
  },
  {
    code: "CD",
    code3: "COD",
    flag: "/flags/cd.svg",
    name: "Congo, Democratic Republic of the",
    phoneCode: "243",
    shortName: "DR Congo",
  },
  {
    code: "CF",
    code3: "CAF",
    flag: "/flags/cf.svg",
    name: "Central African Republic",
    phoneCode: "236",
    shortName: "Central African Republic",
  },
  {
    code: "CG",
    code3: "COG",
    flag: "/flags/cg.svg",
    name: "Congo",
    phoneCode: "242",
    shortName: "Congo",
  },
  {
    code: "CH",
    code3: "CHE",
    flag: "/flags/ch.svg",
    name: "Switzerland",
    phoneCode: "41",
    shortName: "Switzerland",
  },
  {
    code: "CI",
    code3: "CIV",
    flag: "/flags/ci.svg",
    name: "Côte d'Ivoire",
    phoneCode: "225",
    shortName: "Côte d'Ivoire",
  },
  {
    code: "CK",
    code3: "COK",
    flag: "/flags/ck.svg",
    name: "Cook Islands",
    phoneCode: "682",
    shortName: "Cook Islands",
  },
  {
    code: "CL",
    code3: "CHL",
    flag: "/flags/cl.svg",
    name: "Chile",
    phoneCode: "56",
    shortName: "Chile",
  },
  {
    code: "CM",
    code3: "CMR",
    flag: "/flags/cm.svg",
    name: "Cameroon",
    phoneCode: "237",
    shortName: "Cameroon",
  },
  {
    code: "CN",
    code3: "CHN",
    flag: "/flags/cn.svg",
    name: "China",
    phoneCode: "86",
    shortName: "China",
  },
  {
    code: "CO",
    code3: "COL",
    flag: "/flags/co.svg",
    name: "Colombia",
    phoneCode: "57",
    shortName: "Colombia",
  },
  {
    code: "CR",
    code3: "CRI",
    flag: "/flags/cr.svg",
    name: "Costa Rica",
    phoneCode: "506",
    shortName: "Costa Rica",
  },
  {
    code: "CU",
    code3: "CUB",
    flag: "/flags/cu.svg",
    name: "Cuba",
    phoneCode: "53",
    shortName: "Cuba",
  },
  {
    code: "CV",
    code3: "CPV",
    flag: "/flags/cv.svg",
    name: "Cabo Verde",
    phoneCode: "238",
    shortName: "Cabo Verde",
  },
  {
    code: "CW",
    code3: "CUW",
    flag: "/flags/cw.svg",
    name: "Curaçao",
    phoneCode: "599",
    shortName: "Curaçao",
  },
  {
    code: "CX",
    code3: "CXR",
    flag: "/flags/cx.svg",
    name: "Christmas Island",
    phoneCode: "61",
    shortName: "Christmas Island",
  },
  {
    code: "CY",
    code3: "CYP",
    flag: "/flags/cy.svg",
    name: "Cyprus",
    phoneCode: "357",
    shortName: "Cyprus",
  },
  {
    code: "CZ",
    code3: "CZE",
    flag: "/flags/cz.svg",
    name: "Czechia",
    phoneCode: "420",
    shortName: "Czechia",
  },
  {
    code: "DE",
    code3: "DEU",
    flag: "/flags/de.svg",
    name: "Germany",
    phoneCode: "49",
    shortName: "Germany",
  },
  {
    code: "DJ",
    code3: "DJI",
    flag: "/flags/dj.svg",
    name: "Djibouti",
    phoneCode: "253",
    shortName: "Djibouti",
  },
  {
    code: "DK",
    code3: "DNK",
    flag: "/flags/dk.svg",
    name: "Denmark",
    phoneCode: "45",
    shortName: "Denmark",
  },
  {
    code: "DM",
    code3: "DMA",
    flag: "/flags/dm.svg",
    name: "Dominica",
    phoneCode: "1767",
    shortName: "Dominica",
  },
  {
    code: "DO",
    code3: "DOM",
    flag: "/flags/do.svg",
    name: "Dominican Republic",
    phoneCode: "1809",
    shortName: "Dominican Republic",
  },
  {
    code: "DZ",
    code3: "DZA",
    flag: "/flags/dz.svg",
    name: "Algeria",
    phoneCode: "213",
    shortName: "Algeria",
  },
  {
    code: "EC",
    code3: "ECU",
    flag: "/flags/ec.svg",
    name: "Ecuador",
    phoneCode: "593",
    shortName: "Ecuador",
  },
  {
    code: "EE",
    code3: "EST",
    flag: "/flags/ee.svg",
    name: "Estonia",
    phoneCode: "372",
    shortName: "Estonia",
  },
  {
    code: "EG",
    code3: "EGY",
    flag: "/flags/eg.svg",
    name: "Egypt",
    phoneCode: "20",
    shortName: "Egypt",
  },
  {
    code: "EH",
    code3: "ESH",
    flag: "/flags/eh.svg",
    name: "Western Sahara",
    phoneCode: "212",
    shortName: "Western Sahara",
  },
  {
    code: "ER",
    code3: "ERI",
    flag: "/flags/er.svg",
    name: "Eritrea",
    phoneCode: "291",
    shortName: "Eritrea",
  },
  {
    code: "ES",
    code3: "ESP",
    flag: "/flags/es.svg",
    name: "Spain",
    phoneCode: "34",
    shortName: "Spain",
  },
  {
    code: "ET",
    code3: "ETH",
    flag: "/flags/et.svg",
    name: "Ethiopia",
    phoneCode: "251",
    shortName: "Ethiopia",
  },
  {
    code: "FI",
    code3: "FIN",
    flag: "/flags/fi.svg",
    name: "Finland",
    phoneCode: "358",
    shortName: "Finland",
  },
  {
    code: "FJ",
    code3: "FJI",
    flag: "/flags/fj.svg",
    name: "Fiji",
    phoneCode: "679",
    shortName: "Fiji",
  },
  {
    code: "FK",
    code3: "FLK",
    flag: "/flags/fk.svg",
    name: "Falkland Islands (Malvinas)",
    phoneCode: "500",
    shortName: "Falkland Islands (Malvinas)",
  },
  {
    code: "FM",
    code3: "FSM",
    flag: "/flags/fm.svg",
    name: "Micronesia, Federated States of",
    phoneCode: "691",
    shortName: "Micronesia",
  },
  {
    code: "FO",
    code3: "FRO",
    flag: "/flags/fo.svg",
    name: "Faroe Islands",
    phoneCode: "298",
    shortName: "Faroe Islands",
  },
  {
    code: "FR",
    code3: "FRA",
    flag: "/flags/fr.svg",
    name: "France",
    phoneCode: "33",
    shortName: "France",
  },
  {
    code: "GA",
    code3: "GAB",
    flag: "/flags/ga.svg",
    name: "Gabon",
    phoneCode: "241",
    shortName: "Gabon",
  },
  {
    code: "GB",
    code3: "GBR",
    flag: "/flags/gb.svg",
    name: "United Kingdom",
    phoneCode: "44",
    shortName: "United Kingdom",
  },
  {
    code: "GD",
    code3: "GRD",
    flag: "/flags/gd.svg",
    name: "Grenada",
    phoneCode: "1473",
    shortName: "Grenada",
  },
  {
    code: "GE",
    code3: "GEO",
    flag: "/flags/ge.svg",
    name: "Georgia",
    phoneCode: "995",
    shortName: "Georgia",
  },
  {
    code: "GF",
    code3: "GUF",
    flag: "/flags/gf.svg",
    name: "French Guiana",
    phoneCode: "594",
    shortName: "French Guiana",
  },
  {
    code: "GG",
    code3: "GGY",
    flag: "/flags/gg.svg",
    name: "Guernsey",
    phoneCode: "44",
    shortName: "Guernsey",
  },
  {
    code: "GH",
    code3: "GHA",
    flag: "/flags/gh.svg",
    name: "Ghana",
    phoneCode: "233",
    shortName: "Ghana",
  },
  {
    code: "GI",
    code3: "GIB",
    flag: "/flags/gi.svg",
    name: "Gibraltar",
    phoneCode: "350",
    shortName: "Gibraltar",
  },
  {
    code: "GL",
    code3: "GRL",
    flag: "/flags/gl.svg",
    name: "Greenland",
    phoneCode: "299",
    shortName: "Greenland",
  },
  {
    code: "GM",
    code3: "GMB",
    flag: "/flags/gm.svg",
    name: "Gambia",
    phoneCode: "220",
    shortName: "Gambia",
  },
  {
    code: "GN",
    code3: "GIN",
    flag: "/flags/gn.svg",
    name: "Guinea",
    phoneCode: "224",
    shortName: "Guinea",
  },
  {
    code: "GP",
    code3: "GLP",
    flag: "/flags/gp.svg",
    name: "Guadeloupe",
    phoneCode: "590",
    shortName: "Guadeloupe",
  },
  {
    code: "GQ",
    code3: "GNQ",
    flag: "/flags/gq.svg",
    name: "Equatorial Guinea",
    phoneCode: "240",
    shortName: "Equatorial Guinea",
  },
  {
    code: "GR",
    code3: "GRC",
    flag: "/flags/gr.svg",
    name: "Greece",
    phoneCode: "30",
    shortName: "Greece",
  },
  {
    code: "GS",
    code3: "SGS",
    flag: "/flags/gs.svg",
    name: "South Georgia and the South Sandwich Islands",
    phoneCode: "500",
    shortName: "South Georgia and the South Sandwich Islands",
  },
  {
    code: "GT",
    code3: "GTM",
    flag: "/flags/gt.svg",
    name: "Guatemala",
    phoneCode: "502",
    shortName: "Guatemala",
  },
  {
    code: "GU",
    code3: "GUM",
    flag: "/flags/gu.svg",
    name: "Guam",
    phoneCode: "1671",
    shortName: "Guam",
  },
  {
    code: "GW",
    code3: "GNB",
    flag: "/flags/gw.svg",
    name: "Guinea-Bissau",
    phoneCode: "245",
    shortName: "Guinea-Bissau",
  },
  {
    code: "GY",
    code3: "GUY",
    flag: "/flags/gy.svg",
    name: "Guyana",
    phoneCode: "592",
    shortName: "Guyana",
  },
  {
    code: "HK",
    code3: "HKG",
    flag: "/flags/hk.svg",
    name: "Hong Kong",
    phoneCode: "852",
    shortName: "Hong Kong",
  },
  {
    code: "HM",
    code3: "HMD",
    flag: "/flags/hm.svg",
    name: "Heard Island and McDonald Islands",
    phoneCode: "672",
    shortName: "Heard Island and McDonald Islands",
  },
  {
    code: "HN",
    code3: "HND",
    flag: "/flags/hn.svg",
    name: "Honduras",
    phoneCode: "504",
    shortName: "Honduras",
  },
  {
    code: "HR",
    code3: "HRV",
    flag: "/flags/hr.svg",
    name: "Croatia",
    phoneCode: "385",
    shortName: "Croatia",
  },
  {
    code: "HT",
    code3: "HTI",
    flag: "/flags/ht.svg",
    name: "Haiti",
    phoneCode: "509",
    shortName: "Haiti",
  },
  {
    code: "HU",
    code3: "HUN",
    flag: "/flags/hu.svg",
    name: "Hungary",
    phoneCode: "36",
    shortName: "Hungary",
  },
  {
    code: "ID",
    code3: "IDN",
    flag: "/flags/id.svg",
    name: "Indonesia",
    phoneCode: "62",
    shortName: "Indonesia",
  },
  {
    code: "IE",
    code3: "IRL",
    flag: "/flags/ie.svg",
    name: "Ireland",
    phoneCode: "353",
    shortName: "Ireland",
  },
  {
    code: "IL",
    code3: "ISR",
    flag: "/flags/il.svg",
    name: "Israel",
    phoneCode: "972",
    shortName: "Israel",
  },
  {
    code: "IM",
    code3: "IMN",
    flag: "/flags/im.svg",
    name: "Isle of Man",
    phoneCode: "44",
    shortName: "Isle of Man",
  },
  {
    code: "IN",
    code3: "IND",
    flag: "/flags/in.svg",
    name: "India",
    phoneCode: "91",
    shortName: "India",
  },
  {
    code: "IO",
    code3: "IOT",
    flag: "/flags/io.svg",
    name: "British Indian Ocean Territory",
    phoneCode: "246",
    shortName: "British Indian Ocean Territory",
  },
  {
    code: "IQ",
    code3: "IRQ",
    flag: "/flags/iq.svg",
    name: "Iraq",
    phoneCode: "964",
    shortName: "Iraq",
  },
  {
    code: "IR",
    code3: "IRN",
    flag: "/flags/ir.svg",
    name: "Iran, Islamic Republic of",
    phoneCode: "98",
    shortName: "Iran",
  },
  {
    code: "IS",
    code3: "ISL",
    flag: "/flags/is.svg",
    name: "Iceland",
    phoneCode: "354",
    shortName: "Iceland",
  },
  {
    code: "IT",
    code3: "ITA",
    flag: "/flags/it.svg",
    name: "Italy",
    phoneCode: "39",
    shortName: "Italy",
  },
  {
    code: "JE",
    code3: "JEY",
    flag: "/flags/je.svg",
    name: "Jersey",
    phoneCode: "44",
    shortName: "Jersey",
  },
  {
    code: "JM",
    code3: "JAM",
    flag: "/flags/jm.svg",
    name: "Jamaica",
    phoneCode: "1876",
    shortName: "Jamaica",
  },
  {
    code: "JO",
    code3: "JOR",
    flag: "/flags/jo.svg",
    name: "Jordan",
    phoneCode: "962",
    shortName: "Jordan",
  },
  {
    code: "JP",
    code3: "JPN",
    flag: "/flags/jp.svg",
    name: "Japan",
    phoneCode: "81",
    shortName: "Japan",
  },
  {
    code: "KE",
    code3: "KEN",
    flag: "/flags/ke.svg",
    name: "Kenya",
    phoneCode: "254",
    shortName: "Kenya",
  },
  {
    code: "KG",
    code3: "KGZ",
    flag: "/flags/kg.svg",
    name: "Kyrgyzstan",
    phoneCode: "996",
    shortName: "Kyrgyzstan",
  },
  {
    code: "KH",
    code3: "KHM",
    flag: "/flags/kh.svg",
    name: "Cambodia",
    phoneCode: "855",
    shortName: "Cambodia",
  },
  {
    code: "KI",
    code3: "KIR",
    flag: "/flags/ki.svg",
    name: "Kiribati",
    phoneCode: "686",
    shortName: "Kiribati",
  },
  {
    code: "KM",
    code3: "COM",
    flag: "/flags/km.svg",
    name: "Comoros",
    phoneCode: "269",
    shortName: "Comoros",
  },
  {
    code: "KN",
    code3: "KNA",
    flag: "/flags/kn.svg",
    name: "Saint Kitts and Nevis",
    phoneCode: "1869",
    shortName: "Saint Kitts and Nevis",
  },
  {
    code: "KP",
    code3: "PRK",
    flag: "/flags/kp.svg",
    name: "Korea, Democratic People's Republic of",
    phoneCode: "850",
    shortName: "North Korea",
  },
  {
    code: "KR",
    code3: "KOR",
    flag: "/flags/kr.svg",
    name: "Korea, Republic of",
    phoneCode: "82",
    shortName: "South Korea",
  },
  {
    code: "KW",
    code3: "KWT",
    flag: "/flags/kw.svg",
    name: "Kuwait",
    phoneCode: "965",
    shortName: "Kuwait",
  },
  {
    code: "KY",
    code3: "CYM",
    flag: "/flags/ky.svg",
    name: "Cayman Islands",
    phoneCode: "1345",
    shortName: "Cayman Islands",
  },
  {
    code: "KZ",
    code3: "KAZ",
    flag: "/flags/kz.svg",
    name: "Kazakhstan",
    phoneCode: "7",
    shortName: "Kazakhstan",
  },
  {
    code: "LA",
    code3: "LAO",
    flag: "/flags/la.svg",
    name: "Lao People's Democratic Republic",
    phoneCode: "856",
    shortName: "Laos",
  },
  {
    code: "LB",
    code3: "LBN",
    flag: "/flags/lb.svg",
    name: "Lebanon",
    phoneCode: "961",
    shortName: "Lebanon",
  },
  {
    code: "LC",
    code3: "LCA",
    flag: "/flags/lc.svg",
    name: "Saint Lucia",
    phoneCode: "1758",
    shortName: "Saint Lucia",
  },
  {
    code: "LI",
    code3: "LIE",
    flag: "/flags/li.svg",
    name: "Liechtenstein",
    phoneCode: "423",
    shortName: "Liechtenstein",
  },
  {
    code: "LK",
    code3: "LKA",
    flag: "/flags/lk.svg",
    name: "Sri Lanka",
    phoneCode: "94",
    shortName: "Sri Lanka",
  },
  {
    code: "LR",
    code3: "LBR",
    flag: "/flags/lr.svg",
    name: "Liberia",
    phoneCode: "231",
    shortName: "Liberia",
  },
  {
    code: "LS",
    code3: "LSO",
    flag: "/flags/ls.svg",
    name: "Lesotho",
    phoneCode: "266",
    shortName: "Lesotho",
  },
  {
    code: "LT",
    code3: "LTU",
    flag: "/flags/lt.svg",
    name: "Lithuania",
    phoneCode: "370",
    shortName: "Lithuania",
  },
  {
    code: "LU",
    code3: "LUX",
    flag: "/flags/lu.svg",
    name: "Luxembourg",
    phoneCode: "352",
    shortName: "Luxembourg",
  },
  {
    code: "LV",
    code3: "LVA",
    flag: "/flags/lv.svg",
    name: "Latvia",
    phoneCode: "371",
    shortName: "Latvia",
  },
  {
    code: "LY",
    code3: "LBY",
    flag: "/flags/ly.svg",
    name: "Libya",
    phoneCode: "218",
    shortName: "Libya",
  },
  {
    code: "MA",
    code3: "MAR",
    flag: "/flags/ma.svg",
    name: "Morocco",
    phoneCode: "212",
    shortName: "Morocco",
  },
  {
    code: "MC",
    code3: "MCO",
    flag: "/flags/mc.svg",
    name: "Monaco",
    phoneCode: "377",
    shortName: "Monaco",
  },
  {
    code: "MD",
    code3: "MDA",
    flag: "/flags/md.svg",
    name: "Moldova, Republic of",
    phoneCode: "373",
    shortName: "Moldova",
  },
  {
    code: "ME",
    code3: "MNE",
    flag: "/flags/me.svg",
    name: "Montenegro",
    phoneCode: "382",
    shortName: "Montenegro",
  },
  {
    code: "MF",
    code3: "MAF",
    flag: "/flags/mf.svg",
    name: "Saint Martin (French part)",
    phoneCode: "590",
    shortName: "Saint Martin (French part)",
  },
  {
    code: "MG",
    code3: "MDG",
    flag: "/flags/mg.svg",
    name: "Madagascar",
    phoneCode: "261",
    shortName: "Madagascar",
  },
  {
    code: "MH",
    code3: "MHL",
    flag: "/flags/mh.svg",
    name: "Marshall Islands",
    phoneCode: "692",
    shortName: "Marshall Islands",
  },
  {
    code: "MK",
    code3: "MKD",
    flag: "/flags/mk.svg",
    name: "North Macedonia",
    phoneCode: "389",
    shortName: "North Macedonia",
  },
  {
    code: "ML",
    code3: "MLI",
    flag: "/flags/ml.svg",
    name: "Mali",
    phoneCode: "223",
    shortName: "Mali",
  },
  {
    code: "MM",
    code3: "MMR",
    flag: "/flags/mm.svg",
    name: "Myanmar",
    phoneCode: "95",
    shortName: "Myanmar",
  },
  {
    code: "MN",
    code3: "MNG",
    flag: "/flags/mn.svg",
    name: "Mongolia",
    phoneCode: "976",
    shortName: "Mongolia",
  },
  {
    code: "MO",
    code3: "MAC",
    flag: "/flags/mo.svg",
    name: "Macao",
    phoneCode: "853",
    shortName: "Macao",
  },
  {
    code: "MP",
    code3: "MNP",
    flag: "/flags/mp.svg",
    name: "Northern Mariana Islands",
    phoneCode: "1670",
    shortName: "Northern Mariana Islands",
  },
  {
    code: "MQ",
    code3: "MTQ",
    flag: "/flags/mq.svg",
    name: "Martinique",
    phoneCode: "596",
    shortName: "Martinique",
  },
  {
    code: "MR",
    code3: "MRT",
    flag: "/flags/mr.svg",
    name: "Mauritania",
    phoneCode: "222",
    shortName: "Mauritania",
  },
  {
    code: "MS",
    code3: "MSR",
    flag: "/flags/ms.svg",
    name: "Montserrat",
    phoneCode: "1664",
    shortName: "Montserrat",
  },
  {
    code: "MT",
    code3: "MLT",
    flag: "/flags/mt.svg",
    name: "Malta",
    phoneCode: "356",
    shortName: "Malta",
  },
  {
    code: "MU",
    code3: "MUS",
    flag: "/flags/mu.svg",
    name: "Mauritius",
    phoneCode: "230",
    shortName: "Mauritius",
  },
  {
    code: "MV",
    code3: "MDV",
    flag: "/flags/mv.svg",
    name: "Maldives",
    phoneCode: "960",
    shortName: "Maldives",
  },
  {
    code: "MW",
    code3: "MWI",
    flag: "/flags/mw.svg",
    name: "Malawi",
    phoneCode: "265",
    shortName: "Malawi",
  },
  {
    code: "MX",
    code3: "MEX",
    flag: "/flags/mx.svg",
    name: "Mexico",
    phoneCode: "52",
    shortName: "Mexico",
  },
  {
    code: "MY",
    code3: "MYS",
    flag: "/flags/my.svg",
    name: "Malaysia",
    phoneCode: "60",
    shortName: "Malaysia",
  },
  {
    code: "MZ",
    code3: "MOZ",
    flag: "/flags/mz.svg",
    name: "Mozambique",
    phoneCode: "258",
    shortName: "Mozambique",
  },
  {
    code: "NA",
    code3: "NAM",
    flag: "/flags/na.svg",
    name: "Namibia",
    phoneCode: "264",
    shortName: "Namibia",
  },
  {
    code: "NC",
    code3: "NCL",
    flag: "/flags/nc.svg",
    name: "New Caledonia",
    phoneCode: "687",
    shortName: "New Caledonia",
  },
  {
    code: "NE",
    code3: "NER",
    flag: "/flags/ne.svg",
    name: "Niger",
    phoneCode: "227",
    shortName: "Niger",
  },
  {
    code: "NF",
    code3: "NFK",
    flag: "/flags/nf.svg",
    name: "Norfolk Island",
    phoneCode: "672",
    shortName: "Norfolk Island",
  },
  {
    code: "NG",
    code3: "NGA",
    flag: "/flags/ng.svg",
    name: "Nigeria",
    phoneCode: "234",
    shortName: "Nigeria",
  },
  {
    code: "NI",
    code3: "NIC",
    flag: "/flags/ni.svg",
    name: "Nicaragua",
    phoneCode: "505",
    shortName: "Nicaragua",
  },
  {
    code: "NL",
    code3: "NLD",
    flag: "/flags/nl.svg",
    name: "Netherlands",
    phoneCode: "31",
    shortName: "Netherlands",
  },
  {
    code: "NO",
    code3: "NOR",
    flag: "/flags/no.svg",
    name: "Norway",
    phoneCode: "47",
    shortName: "Norway",
  },
  {
    code: "NP",
    code3: "NPL",
    flag: "/flags/np.svg",
    name: "Nepal",
    phoneCode: "977",
    shortName: "Nepal",
  },
  {
    code: "NR",
    code3: "NRU",
    flag: "/flags/nr.svg",
    name: "Nauru",
    phoneCode: "674",
    shortName: "Nauru",
  },
  {
    code: "NU",
    code3: "NIU",
    flag: "/flags/nu.svg",
    name: "Niue",
    phoneCode: "683",
    shortName: "Niue",
  },
  {
    code: "NZ",
    code3: "NZL",
    flag: "/flags/nz.svg",
    name: "New Zealand",
    phoneCode: "64",
    shortName: "New Zealand",
  },
  {
    code: "OM",
    code3: "OMN",
    flag: "/flags/om.svg",
    name: "Oman",
    phoneCode: "968",
    shortName: "Oman",
  },
  {
    code: "PA",
    code3: "PAN",
    flag: "/flags/pa.svg",
    name: "Panama",
    phoneCode: "507",
    shortName: "Panama",
  },
  {
    code: "PE",
    code3: "PER",
    flag: "/flags/pe.svg",
    name: "Peru",
    phoneCode: "51",
    shortName: "Peru",
  },
  {
    code: "PF",
    code3: "PYF",
    flag: "/flags/pf.svg",
    name: "French Polynesia",
    phoneCode: "689",
    shortName: "French Polynesia",
  },
  {
    code: "PG",
    code3: "PNG",
    flag: "/flags/pg.svg",
    name: "Papua New Guinea",
    phoneCode: "675",
    shortName: "Papua New Guinea",
  },
  {
    code: "PH",
    code3: "PHL",
    flag: "/flags/ph.svg",
    name: "Philippines",
    phoneCode: "63",
    shortName: "Philippines",
  },
  {
    code: "PK",
    code3: "PAK",
    flag: "/flags/pk.svg",
    name: "Pakistan",
    phoneCode: "92",
    shortName: "Pakistan",
  },
  {
    code: "PL",
    code3: "POL",
    flag: "/flags/pl.svg",
    name: "Poland",
    phoneCode: "48",
    shortName: "Poland",
  },
  {
    code: "PM",
    code3: "SPM",
    flag: "/flags/pm.svg",
    name: "Saint Pierre and Miquelon",
    phoneCode: "508",
    shortName: "Saint Pierre and Miquelon",
  },
  {
    code: "PN",
    code3: "PCN",
    flag: "/flags/pn.svg",
    name: "Pitcairn",
    phoneCode: "870",
    shortName: "Pitcairn",
  },
  {
    code: "PR",
    code3: "PRI",
    flag: "/flags/pr.svg",
    name: "Puerto Rico",
    phoneCode: "1787",
    shortName: "Puerto Rico",
  },
  {
    code: "PS",
    code3: "PSE",
    flag: "/flags/ps.svg",
    name: "Palestine, State of",
    phoneCode: "970",
    shortName: "Palestine",
  },
  {
    code: "PT",
    code3: "PRT",
    flag: "/flags/pt.svg",
    name: "Portugal",
    phoneCode: "351",
    shortName: "Portugal",
  },
  {
    code: "PW",
    code3: "PLW",
    flag: "/flags/pw.svg",
    name: "Palau",
    phoneCode: "680",
    shortName: "Palau",
  },
  {
    code: "PY",
    code3: "PRY",
    flag: "/flags/py.svg",
    name: "Paraguay",
    phoneCode: "595",
    shortName: "Paraguay",
  },
  {
    code: "QA",
    code3: "QAT",
    flag: "/flags/qa.svg",
    name: "Qatar",
    phoneCode: "974",
    shortName: "Qatar",
  },
  {
    code: "RE",
    code3: "REU",
    flag: "/flags/re.svg",
    name: "Réunion",
    phoneCode: "262",
    shortName: "Réunion",
  },
  {
    code: "RO",
    code3: "ROU",
    flag: "/flags/ro.svg",
    name: "Romania",
    phoneCode: "40",
    shortName: "Romania",
  },
  {
    code: "RS",
    code3: "SRB",
    flag: "/flags/rs.svg",
    name: "Serbia",
    phoneCode: "381",
    shortName: "Serbia",
  },
  {
    code: "RU",
    code3: "RUS",
    flag: "/flags/ru.svg",
    name: "Russian Federation",
    phoneCode: "7",
    shortName: "Russia",
  },
  {
    code: "RW",
    code3: "RWA",
    flag: "/flags/rw.svg",
    name: "Rwanda",
    phoneCode: "250",
    shortName: "Rwanda",
  },
  {
    code: "SA",
    code3: "SAU",
    flag: "/flags/sa.svg",
    name: "Saudi Arabia",
    phoneCode: "966",
    shortName: "Saudi Arabia",
  },
  {
    code: "SB",
    code3: "SLB",
    flag: "/flags/sb.svg",
    name: "Solomon Islands",
    phoneCode: "677",
    shortName: "Solomon Islands",
  },
  {
    code: "SC",
    code3: "SYC",
    flag: "/flags/sc.svg",
    name: "Seychelles",
    phoneCode: "248",
    shortName: "Seychelles",
  },
  {
    code: "SD",
    code3: "SDN",
    flag: "/flags/sd.svg",
    name: "Sudan",
    phoneCode: "249",
    shortName: "Sudan",
  },
  {
    code: "SE",
    code3: "SWE",
    flag: "/flags/se.svg",
    name: "Sweden",
    phoneCode: "46",
    shortName: "Sweden",
  },
  {
    code: "SG",
    code3: "SGP",
    flag: "/flags/sg.svg",
    name: "Singapore",
    phoneCode: "65",
    shortName: "Singapore",
  },
  {
    code: "SH",
    code3: "SHN",
    flag: "/flags/sh.svg",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    phoneCode: "290",
    shortName: "Saint Helena, Ascension and Tristan da Cunha",
  },
  {
    code: "SI",
    code3: "SVN",
    flag: "/flags/si.svg",
    name: "Slovenia",
    phoneCode: "386",
    shortName: "Slovenia",
  },
  {
    code: "SJ",
    code3: "SJM",
    flag: "/flags/sj.svg",
    name: "Svalbard and Jan Mayen",
    phoneCode: "47",
    shortName: "Svalbard and Jan Mayen",
  },
  {
    code: "SK",
    code3: "SVK",
    flag: "/flags/sk.svg",
    name: "Slovakia",
    phoneCode: "421",
    shortName: "Slovakia",
  },
  {
    code: "SL",
    code3: "SLE",
    flag: "/flags/sl.svg",
    name: "Sierra Leone",
    phoneCode: "232",
    shortName: "Sierra Leone",
  },
  {
    code: "SM",
    code3: "SMR",
    flag: "/flags/sm.svg",
    name: "San Marino",
    phoneCode: "378",
    shortName: "San Marino",
  },
  {
    code: "SN",
    code3: "SEN",
    flag: "/flags/sn.svg",
    name: "Senegal",
    phoneCode: "221",
    shortName: "Senegal",
  },
  {
    code: "SO",
    code3: "SOM",
    flag: "/flags/so.svg",
    name: "Somalia",
    phoneCode: "252",
    shortName: "Somalia",
  },
  {
    code: "SR",
    code3: "SUR",
    flag: "/flags/sr.svg",
    name: "Suriname",
    phoneCode: "597",
    shortName: "Suriname",
  },
  {
    code: "SS",
    code3: "SSD",
    flag: "/flags/ss.svg",
    name: "South Sudan",
    phoneCode: "211",
    shortName: "South Sudan",
  },
  {
    code: "ST",
    code3: "STP",
    flag: "/flags/st.svg",
    name: "Sao Tome and Principe",
    phoneCode: "239",
    shortName: "Sao Tome and Principe",
  },
  {
    code: "SV",
    code3: "SLV",
    flag: "/flags/sv.svg",
    name: "El Salvador",
    phoneCode: "503",
    shortName: "El Salvador",
  },
  {
    code: "SX",
    code3: "SXM",
    flag: "/flags/sx.svg",
    name: "Sint Maarten (Dutch part)",
    phoneCode: "1721",
    shortName: "Sint Maarten (Dutch part)",
  },
  {
    code: "SY",
    code3: "SYR",
    flag: "/flags/sy.svg",
    name: "Syrian Arab Republic",
    phoneCode: "963",
    shortName: "Syria",
  },
  {
    code: "SZ",
    code3: "SWZ",
    flag: "/flags/sz.svg",
    name: "Eswatini",
    phoneCode: "268",
    shortName: "Eswatini",
  },
  {
    code: "TC",
    code3: "TCA",
    flag: "/flags/tc.svg",
    name: "Turks and Caicos Islands",
    phoneCode: "1649",
    shortName: "Turks and Caicos Islands",
  },
  {
    code: "TD",
    code3: "TCD",
    flag: "/flags/td.svg",
    name: "Chad",
    phoneCode: "235",
    shortName: "Chad",
  },
  {
    code: "TF",
    code3: "ATF",
    flag: "/flags/tf.svg",
    name: "French Southern Territories",
    phoneCode: "262",
    shortName: "French Southern Territories",
  },
  {
    code: "TG",
    code3: "TGO",
    flag: "/flags/tg.svg",
    name: "Togo",
    phoneCode: "228",
    shortName: "Togo",
  },
  {
    code: "TH",
    code3: "THA",
    flag: "/flags/th.svg",
    name: "Thailand",
    phoneCode: "66",
    shortName: "Thailand",
  },
  {
    code: "TJ",
    code3: "TJK",
    flag: "/flags/tj.svg",
    name: "Tajikistan",
    phoneCode: "992",
    shortName: "Tajikistan",
  },
  {
    code: "TK",
    code3: "TKL",
    flag: "/flags/tk.svg",
    name: "Tokelau",
    phoneCode: "690",
    shortName: "Tokelau",
  },
  {
    code: "TL",
    code3: "TLS",
    flag: "/flags/tl.svg",
    name: "Timor-Leste",
    phoneCode: "670",
    shortName: "Timor-Leste",
  },
  {
    code: "TM",
    code3: "TKM",
    flag: "/flags/tm.svg",
    name: "Turkmenistan",
    phoneCode: "993",
    shortName: "Turkmenistan",
  },
  {
    code: "TN",
    code3: "TUN",
    flag: "/flags/tn.svg",
    name: "Tunisia",
    phoneCode: "216",
    shortName: "Tunisia",
  },
  {
    code: "TO",
    code3: "TON",
    flag: "/flags/to.svg",
    name: "Tonga",
    phoneCode: "676",
    shortName: "Tonga",
  },
  {
    code: "TR",
    code3: "TUR",
    flag: "/flags/tr.svg",
    name: "Turkey",
    phoneCode: "90",
    shortName: "Turkey",
  },
  {
    code: "TT",
    code3: "TTO",
    flag: "/flags/tt.svg",
    name: "Trinidad and Tobago",
    phoneCode: "1868",
    shortName: "Trinidad and Tobago",
  },
  {
    code: "TV",
    code3: "TUV",
    flag: "/flags/tv.svg",
    name: "Tuvalu",
    phoneCode: "688",
    shortName: "Tuvalu",
  },
  {
    code: "TW",
    code3: "TWN",
    flag: "/flags/tw.svg",
    name: "Taiwan, Province of China",
    phoneCode: "886",
    shortName: "Taiwan",
  },
  {
    code: "TZ",
    code3: "TZA",
    flag: "/flags/tz.svg",
    name: "Tanzania, United Republic of",
    phoneCode: "255",
    shortName: "Tanzania",
  },
  {
    code: "UA",
    code3: "UKR",
    flag: "/flags/ua.svg",
    name: "Ukraine",
    phoneCode: "380",
    shortName: "Ukraine",
  },
  {
    code: "UG",
    code3: "UGA",
    flag: "/flags/ug.svg",
    name: "Uganda",
    phoneCode: "256",
    shortName: "Uganda",
  },
  {
    code: "UM",
    code3: "UMI",
    flag: "/flags/um.svg",
    name: "United States Minor Outlying Islands",
    phoneCode: "1",
    shortName: "United States Minor Outlying Islands",
  },
  {
    code: "US",
    code3: "USA",
    flag: "/flags/us.svg",
    name: "United States of America",
    phoneCode: "1",
    shortName: "United States",
  },
  {
    code: "UY",
    code3: "URY",
    flag: "/flags/uy.svg",
    name: "Uruguay",
    phoneCode: "598",
    shortName: "Uruguay",
  },
  {
    code: "UZ",
    code3: "UZB",
    flag: "/flags/uz.svg",
    name: "Uzbekistan",
    phoneCode: "998",
    shortName: "Uzbekistan",
  },
  {
    code: "VA",
    code3: "VAT",
    flag: "/flags/va.svg",
    name: "Holy See",
    phoneCode: "39",
    shortName: "Holy See",
  },
  {
    code: "VC",
    code3: "VCT",
    flag: "/flags/vc.svg",
    name: "Saint Vincent and the Grenadines",
    phoneCode: "1784",
    shortName: "Saint Vincent and the Grenadines",
  },
  {
    code: "VE",
    code3: "VEN",
    flag: "/flags/ve.svg",
    name: "Venezuela, Bolivarian Republic of",
    phoneCode: "58",
    shortName: "Venezuela",
  },
  {
    code: "VG",
    code3: "VGB",
    flag: "/flags/vg.svg",
    name: "Virgin Islands, British",
    phoneCode: "1284",
    shortName: "Virgin Islands, British",
  },
  {
    code: "VI",
    code3: "VIR",
    flag: "/flags/vi.svg",
    name: "Virgin Islands, U.S.",
    phoneCode: "1340",
    shortName: "Virgin Islands, U.S.",
  },
  {
    code: "VN",
    code3: "VNM",
    flag: "/flags/vn.svg",
    name: "Viet Nam",
    phoneCode: "84",
    shortName: "Vietnam",
  },
  {
    code: "VU",
    code3: "VUT",
    flag: "/flags/vu.svg",
    name: "Vanuatu",
    phoneCode: "678",
    shortName: "Vanuatu",
  },
  {
    code: "WF",
    code3: "WLF",
    flag: "/flags/wf.svg",
    name: "Wallis and Futuna",
    phoneCode: "681",
    shortName: "Wallis and Futuna",
  },
  {
    code: "WS",
    code3: "WSM",
    flag: "/flags/ws.svg",
    name: "Samoa",
    phoneCode: "685",
    shortName: "Samoa",
  },
  {
    code: "YE",
    code3: "YEM",
    flag: "/flags/ye.svg",
    name: "Yemen",
    phoneCode: "967",
    shortName: "Yemen",
  },
  {
    code: "YT",
    code3: "MYT",
    flag: "/flags/yt.svg",
    name: "Mayotte",
    phoneCode: "262",
    shortName: "Mayotte",
  },
  {
    code: "ZA",
    code3: "ZAF",
    flag: "/flags/za.svg",
    name: "South Africa",
    phoneCode: "27",
    shortName: "South Africa",
  },
  {
    code: "ZM",
    code3: "ZMB",
    flag: "/flags/zm.svg",
    name: "Zambia",
    phoneCode: "260",
    shortName: "Zambia",
  },
  {
    code: "ZW",
    code3: "ZWE",
    flag: "/flags/zw.svg",
    name: "Zimbabwe",
    phoneCode: "263",
    shortName: "Zimbabwe",
  },
] as const;

export type CountryAlpha2Code = (typeof countries)[number]["code"];
